# Generated by Django 5.2.8 on 2025-11-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_country_code', models.CharField(default='+91', max_length=5)),
                ('whatsapp_number', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('amazon_seller', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('brand_owner', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('asin', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
