# Generated by Django 5.2.8 on 2025-11-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UAE', 'UAE'), ('Canada', 'Canada'), ('UK', 'UK'), ('Australia', 'Australia')], default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='whatsapp_country_code',
            field=models.CharField(choices=[('+91', '+91'), ('+1', '+1'), ('+971', '+971'), ('+44', '+44'), ('+61', '+61'), ('+92', '+92')], default='+91', max_length=5),
        ),
    ]
