# Generated by Django 5.2.8 on 2025-11-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsform',
            name='ad_manager',
            field=models.CharField(choices=[('Self', 'Self'), ('Staff', 'Staff'), ('Third Party', 'Third Party')], max_length=15),
        ),
    ]
